/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as StudentsSidRouteImport } from './routes/students.$sid'
import { Route as SubjectsSlugIndexRouteImport } from './routes/subjects.$slug.index'
import { Route as SubjectsSlugTestsRouteImport } from './routes/subjects.$slug.tests'
import { Route as SubjectsSlugOverviewRouteImport } from './routes/subjects.$slug.overview'
import { Route as SubjectsSlugNewsRouteImport } from './routes/subjects.$slug.news'
import { Route as SubjectsSlugGroupsRouteImport } from './routes/subjects.$slug.groups'
import { Route as SubjectsSlugTestsTidRouteImport } from './routes/subjects.$slug.tests.$tid'
import { Route as SubjectsSlugStudentsSidRouteImport } from './routes/subjects.$slug.students.$sid'
import { Route as SubjectsSlugPPageSlugRouteImport } from './routes/subjects.$slug.p.$pageSlug'
import { Route as SubjectsSlugAssignmentsAidRouteImport } from './routes/subjects.$slug.assignments.$aid'

const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const StudentsSidRoute = StudentsSidRouteImport.update({
  id: '/students/$sid',
  path: '/students/$sid',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSlugIndexRoute = SubjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugTestsRoute = SubjectsSlugTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugOverviewRoute = SubjectsSlugOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugNewsRoute = SubjectsSlugNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugGroupsRoute = SubjectsSlugGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugTestsTidRoute = SubjectsSlugTestsTidRouteImport.update({
  id: '/$tid',
  path: '/$tid',
  getParentRoute: () => SubjectsSlugTestsRoute,
} as any)
const SubjectsSlugStudentsSidRoute = SubjectsSlugStudentsSidRouteImport.update({
  id: '/students/$sid',
  path: '/students/$sid',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugPPageSlugRoute = SubjectsSlugPPageSlugRouteImport.update({
  id: '/p/$pageSlug',
  path: '/p/$pageSlug',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugAssignmentsAidRoute =
  SubjectsSlugAssignmentsAidRouteImport.update({
    id: '/assignments/$aid',
    path: '/assignments/$aid',
    getParentRoute: () => SubjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/submissions': typeof SubmissionsRoute
  '/students/$sid': typeof StudentsSidRoute
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$slug/groups': typeof SubjectsSlugGroupsRoute
  '/subjects/$slug/news': typeof SubjectsSlugNewsRoute
  '/subjects/$slug/overview': typeof SubjectsSlugOverviewRoute
  '/subjects/$slug/tests': typeof SubjectsSlugTestsRouteWithChildren
  '/subjects/$slug/': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
  '/subjects/$slug/students/$sid': typeof SubjectsSlugStudentsSidRoute
  '/subjects/$slug/tests/$tid': typeof SubjectsSlugTestsTidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/submissions': typeof SubmissionsRoute
  '/students/$sid': typeof StudentsSidRoute
  '/subjects': typeof SubjectsIndexRoute
  '/subjects/$slug/groups': typeof SubjectsSlugGroupsRoute
  '/subjects/$slug/news': typeof SubjectsSlugNewsRoute
  '/subjects/$slug/overview': typeof SubjectsSlugOverviewRoute
  '/subjects/$slug/tests': typeof SubjectsSlugTestsRouteWithChildren
  '/subjects/$slug': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
  '/subjects/$slug/students/$sid': typeof SubjectsSlugStudentsSidRoute
  '/subjects/$slug/tests/$tid': typeof SubjectsSlugTestsTidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/submissions': typeof SubmissionsRoute
  '/students/$sid': typeof StudentsSidRoute
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$slug/groups': typeof SubjectsSlugGroupsRoute
  '/subjects/$slug/news': typeof SubjectsSlugNewsRoute
  '/subjects/$slug/overview': typeof SubjectsSlugOverviewRoute
  '/subjects/$slug/tests': typeof SubjectsSlugTestsRouteWithChildren
  '/subjects/$slug/': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
  '/subjects/$slug/students/$sid': typeof SubjectsSlugStudentsSidRoute
  '/subjects/$slug/tests/$tid': typeof SubjectsSlugTestsTidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/subjects'
    | '/submissions'
    | '/students/$sid'
    | '/subjects/$slug'
    | '/subjects/'
    | '/subjects/$slug/groups'
    | '/subjects/$slug/news'
    | '/subjects/$slug/overview'
    | '/subjects/$slug/tests'
    | '/subjects/$slug/'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
    | '/subjects/$slug/students/$sid'
    | '/subjects/$slug/tests/$tid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/submissions'
    | '/students/$sid'
    | '/subjects'
    | '/subjects/$slug/groups'
    | '/subjects/$slug/news'
    | '/subjects/$slug/overview'
    | '/subjects/$slug/tests'
    | '/subjects/$slug'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
    | '/subjects/$slug/students/$sid'
    | '/subjects/$slug/tests/$tid'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/subjects'
    | '/submissions'
    | '/students/$sid'
    | '/subjects/$slug'
    | '/subjects/'
    | '/subjects/$slug/groups'
    | '/subjects/$slug/news'
    | '/subjects/$slug/overview'
    | '/subjects/$slug/tests'
    | '/subjects/$slug/'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
    | '/subjects/$slug/students/$sid'
    | '/subjects/$slug/tests/$tid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  SubmissionsRoute: typeof SubmissionsRoute
  StudentsSidRoute: typeof StudentsSidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/students/$sid': {
      id: '/students/$sid'
      path: '/students/$sid'
      fullPath: '/students/$sid'
      preLoaderRoute: typeof StudentsSidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$slug/': {
      id: '/subjects/$slug/'
      path: '/'
      fullPath: '/subjects/$slug/'
      preLoaderRoute: typeof SubjectsSlugIndexRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/tests': {
      id: '/subjects/$slug/tests'
      path: '/tests'
      fullPath: '/subjects/$slug/tests'
      preLoaderRoute: typeof SubjectsSlugTestsRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/overview': {
      id: '/subjects/$slug/overview'
      path: '/overview'
      fullPath: '/subjects/$slug/overview'
      preLoaderRoute: typeof SubjectsSlugOverviewRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/news': {
      id: '/subjects/$slug/news'
      path: '/news'
      fullPath: '/subjects/$slug/news'
      preLoaderRoute: typeof SubjectsSlugNewsRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/groups': {
      id: '/subjects/$slug/groups'
      path: '/groups'
      fullPath: '/subjects/$slug/groups'
      preLoaderRoute: typeof SubjectsSlugGroupsRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/tests/$tid': {
      id: '/subjects/$slug/tests/$tid'
      path: '/$tid'
      fullPath: '/subjects/$slug/tests/$tid'
      preLoaderRoute: typeof SubjectsSlugTestsTidRouteImport
      parentRoute: typeof SubjectsSlugTestsRoute
    }
    '/subjects/$slug/students/$sid': {
      id: '/subjects/$slug/students/$sid'
      path: '/students/$sid'
      fullPath: '/subjects/$slug/students/$sid'
      preLoaderRoute: typeof SubjectsSlugStudentsSidRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/p/$pageSlug': {
      id: '/subjects/$slug/p/$pageSlug'
      path: '/p/$pageSlug'
      fullPath: '/subjects/$slug/p/$pageSlug'
      preLoaderRoute: typeof SubjectsSlugPPageSlugRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/assignments/$aid': {
      id: '/subjects/$slug/assignments/$aid'
      path: '/assignments/$aid'
      fullPath: '/subjects/$slug/assignments/$aid'
      preLoaderRoute: typeof SubjectsSlugAssignmentsAidRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
  }
}

interface SubjectsSlugTestsRouteChildren {
  SubjectsSlugTestsTidRoute: typeof SubjectsSlugTestsTidRoute
}

const SubjectsSlugTestsRouteChildren: SubjectsSlugTestsRouteChildren = {
  SubjectsSlugTestsTidRoute: SubjectsSlugTestsTidRoute,
}

const SubjectsSlugTestsRouteWithChildren =
  SubjectsSlugTestsRoute._addFileChildren(SubjectsSlugTestsRouteChildren)

interface SubjectsSlugRouteChildren {
  SubjectsSlugGroupsRoute: typeof SubjectsSlugGroupsRoute
  SubjectsSlugNewsRoute: typeof SubjectsSlugNewsRoute
  SubjectsSlugOverviewRoute: typeof SubjectsSlugOverviewRoute
  SubjectsSlugTestsRoute: typeof SubjectsSlugTestsRouteWithChildren
  SubjectsSlugIndexRoute: typeof SubjectsSlugIndexRoute
  SubjectsSlugAssignmentsAidRoute: typeof SubjectsSlugAssignmentsAidRoute
  SubjectsSlugPPageSlugRoute: typeof SubjectsSlugPPageSlugRoute
  SubjectsSlugStudentsSidRoute: typeof SubjectsSlugStudentsSidRoute
}

const SubjectsSlugRouteChildren: SubjectsSlugRouteChildren = {
  SubjectsSlugGroupsRoute: SubjectsSlugGroupsRoute,
  SubjectsSlugNewsRoute: SubjectsSlugNewsRoute,
  SubjectsSlugOverviewRoute: SubjectsSlugOverviewRoute,
  SubjectsSlugTestsRoute: SubjectsSlugTestsRouteWithChildren,
  SubjectsSlugIndexRoute: SubjectsSlugIndexRoute,
  SubjectsSlugAssignmentsAidRoute: SubjectsSlugAssignmentsAidRoute,
  SubjectsSlugPPageSlugRoute: SubjectsSlugPPageSlugRoute,
  SubjectsSlugStudentsSidRoute: SubjectsSlugStudentsSidRoute,
}

const SubjectsSlugRouteWithChildren = SubjectsSlugRoute._addFileChildren(
  SubjectsSlugRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRouteWithChildren
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRouteWithChildren,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  SubmissionsRoute: SubmissionsRoute,
  StudentsSidRoute: StudentsSidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
