/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as SubjectsSlugIndexRouteImport } from './routes/subjects.$slug.index'
import { Route as SubjectsSlugPPageSlugRouteImport } from './routes/subjects.$slug.p.$pageSlug'
import { Route as SubjectsSlugAssignmentsAidRouteImport } from './routes/subjects.$slug.assignments.$aid'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSlugIndexRoute = SubjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugPPageSlugRoute = SubjectsSlugPPageSlugRouteImport.update({
  id: '/p/$pageSlug',
  path: '/p/$pageSlug',
  getParentRoute: () => SubjectsSlugRoute,
} as any)
const SubjectsSlugAssignmentsAidRoute =
  SubjectsSlugAssignmentsAidRouteImport.update({
    id: '/assignments/$aid',
    path: '/assignments/$aid',
    getParentRoute: () => SubjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$slug/': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/subjects': typeof SubjectsIndexRoute
  '/subjects/$slug': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classes': typeof ClassesRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/subjects/$slug': typeof SubjectsSlugRouteWithChildren
  '/subjects/': typeof SubjectsIndexRoute
  '/subjects/$slug/': typeof SubjectsSlugIndexRoute
  '/subjects/$slug/assignments/$aid': typeof SubjectsSlugAssignmentsAidRoute
  '/subjects/$slug/p/$pageSlug': typeof SubjectsSlugPPageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/subjects'
    | '/subjects/$slug'
    | '/subjects/'
    | '/subjects/$slug/'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/subjects'
    | '/subjects/$slug'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classes'
    | '/subjects'
    | '/subjects/$slug'
    | '/subjects/'
    | '/subjects/$slug/'
    | '/subjects/$slug/assignments/$aid'
    | '/subjects/$slug/p/$pageSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClassesRoute: typeof ClassesRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$slug/': {
      id: '/subjects/$slug/'
      path: '/'
      fullPath: '/subjects/$slug/'
      preLoaderRoute: typeof SubjectsSlugIndexRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/p/$pageSlug': {
      id: '/subjects/$slug/p/$pageSlug'
      path: '/p/$pageSlug'
      fullPath: '/subjects/$slug/p/$pageSlug'
      preLoaderRoute: typeof SubjectsSlugPPageSlugRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
    '/subjects/$slug/assignments/$aid': {
      id: '/subjects/$slug/assignments/$aid'
      path: '/assignments/$aid'
      fullPath: '/subjects/$slug/assignments/$aid'
      preLoaderRoute: typeof SubjectsSlugAssignmentsAidRouteImport
      parentRoute: typeof SubjectsSlugRoute
    }
  }
}

interface SubjectsSlugRouteChildren {
  SubjectsSlugIndexRoute: typeof SubjectsSlugIndexRoute
  SubjectsSlugAssignmentsAidRoute: typeof SubjectsSlugAssignmentsAidRoute
  SubjectsSlugPPageSlugRoute: typeof SubjectsSlugPPageSlugRoute
}

const SubjectsSlugRouteChildren: SubjectsSlugRouteChildren = {
  SubjectsSlugIndexRoute: SubjectsSlugIndexRoute,
  SubjectsSlugAssignmentsAidRoute: SubjectsSlugAssignmentsAidRoute,
  SubjectsSlugPPageSlugRoute: SubjectsSlugPPageSlugRoute,
}

const SubjectsSlugRouteWithChildren = SubjectsSlugRoute._addFileChildren(
  SubjectsSlugRouteChildren,
)

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRouteWithChildren
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRouteWithChildren,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClassesRoute: ClassesRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
